### ISSUE TITLE
Controlpanel that clings to the screen side

### ISSUE THREAD

**Issue by Marloan** [XiozZe/XioScript#101]
Like in the earlier versions a controlpanel with the most used functions would be great... so the xio settings can be set quickly... it could also display additional information and a function explaination upon mouseover. 

When you mark only one building it could display the performance of the operation, 
Or a summary of more operations added together.
Or the informations for a whole branch (like you have the marking function now when you click the factory icon.)

To reduce server traffic, the panel could also only execute certain maintainance functions and not all at once... at skillchange only one type of operation needs resetting not all.

**Comment by XiozZe** [comment]
In XS14 the way of using functions has been changed. If you have new or the same suggestions regarding XS14 open a new issue.
