### ISSUE TITLE
change http to https

### ISSUE THREAD

**Issue by cobr123** [XiozZe/XioScript#103]
Virtonomics site and forum goes to https.

```
 @include        http*://*virtonomic*.*/*/*
// @require        https://ajax.googleapis.com/ajax/libs/jquery/1.11.0/jquery.min.js
```

**Comment by XiozZe** [comment]
And fixed.
Thanks!

**Comment by cobr123** [comment]
@require        http**S**://ajax.googleapis.com/ajax/libs/jquery/1.11.0/jquery.min.js

**Comment by XiozZe** [comment]
O well, I might do that one as well.
But does that one have any impact actually?

**Comment by cobr123** [comment]
not sure

**Comment by XiozZe** [comment]
Will be done next update
