### ISSUE TITLE
XS 12.1.5 bug: repair equipment for state enterprises

### ISSUE THREAD

**Issue by TeaMike** [XiozZe/XioScript#109]
It repairs properly but then goes into an endless repair loop reporting Equipment Deals, Equipment Repaired and increase of Equipment Budget despite no further repairs are made (o necessary) during that loop; user must force-quit the script by page reload

**Comment by XiozZe** [comment]
"for state enterprises" means factories etc. are working fine?

**Comment by TeaMike** [comment]
yep

**Comment by XiozZe** [comment]
In XS14, the equipment module is completely reworked. If the same issue still exists, please open a new one.
