### ISSUE TITLE
Suggestion: XS interface

### ISSUE THREAD

**Issue by TeaMike** [XiozZe/XioScript#11]
i'd like to suggest a few optimisations for the XF control panel display:
- show currently installed version number
- keep the panel open on reload
- make the panel floating again
- auto-scroll the XioConsole so user doesn't need to scroll down to see "all done"
- unified button width would make the panel look a lot cleaner

**Comment by XiozZe** [comment]
The new XS12 will only have one button and a log.
Please suggest ideas for the new log as soon as it is ready.

**Comment by TeaMike** [comment]
Right now i can't imagine it being only one button, i'll check it out once available.

**Comment by XiozZe** [comment]
It's already available: check the [XS12 branch](https://github.com/XiozZe/XioScript/tree/XS12).
Install just like XS10.1
In short: every subdivision page has it's own options, and that "maintenance"-button executes all.
Use the console log to check the maintenance progress.
Don't forget to check the [wiki](https://github.com/XiozZe/XioScript/wiki/XS12-Explained).
Just remember it's still work in progress.
