### ISSUE TITLE
XS 12.0.25 doesn't remove "subdivision missing"

### ISSUE THREAD

**Issue by TeaMike** [XiozZe/XioScript#114]
Since upgrading from 12.0.22 to 12.0.25 

"Subdivision (variable number) is missing from the company. Options have been erased from the Local Storage"

For some reason the script isn't able to erase those entries, the message appears on every run of XS for the same set of of subdivisions (which belong to another company due to sale)

**Comment by XiozZe** [comment]
This functionality should be implemented correctly in XS14.

**Comment by XiozZe** [comment]
If there are any problems regarding this in XS14, please open a new issue.
