### ISSUE TITLE
XS 12.0.25 Kindergarten and IT

### ISSUE THREAD

**Issue by Marloan** [XiozZe/XioScript#118]
Hi, would it be possible to add functionality for kindergardens and IT??

Also encountering big problems with scipt functionality on big accounts.... please contact me ingame for further detail.

**Comment by cobr123** [comment]
try this https://github.com/cobr123/XioScript/blob/master/XS12.user.js

**Comment by cobr123** [comment]
try this 12.0.123 https://github.com/cobr123/XioScript/blob/master/XS12.user.js

**Comment by XiozZe** [comment]
Employee and Equipment functions are now supported for Kindergarten and IT in XS14.0.6. Other more specific function have still a long way to go.
