### ISSUE TITLE
XioMaintence Stopping

### ISSUE THREAD

**Issue by kill20** [XiozZe/XioScript#119]
Hi, i'm using the script and, until now i had no problem. But at the moment (a few days ago), the script is not completing the XioMaintence function. It stops at one of the steps.

If i run for each type of building it completes, but running all buildings at the same time causes it to stop.

Best regards,
Giovanne
![capturar](https://cloud.githubusercontent.com/assets/18729903/24247116/1e22c1b6-0fa9-11e7-8ab0-264bcc314ee1.JPG)

**Comment by ezapata20** [comment]
could you please update with this version the new virtonomics oct 16 2017

**Comment by XiozZe** [comment]
Because XS12 will not be supported anymore, I close this issue.
