### ISSUE TITLE
XioScript 12.0.25 now working anymore as of today Oct. 16, 2017

### ISSUE THREAD

**Issue by Ghiby** [XiozZe/XioScript#120]
Hello,

well, I just realized the virto game admins introduced a new "look" as of today, Monday, Oct. 16, 2017, I assume they did some changes in the CSS coding side, to make it look different and with that the 

XioScript | 12.0.25 is not working anymore, at least not for me... 

I'm using Chrome, and I have Tampermonkey and the script is enabled, is on, it was working yesterday just fine, but not today, not anymore

they changed something in the look, the tabs look different, the profile picture looks different with an info button that is interactive and will show links to political party and/or corporation and some other things in the general "look" and feel of the site is different which leads me to believe maybe they did some changes in maybe their HTML and/or CSS coding and even aiming to disable Xio...

please have a look and check it out...

as a side note, on my end, I love Xio, I can handle without it, but since it's available why not use it... and even more, why allow them - the game admins and developers - to prevent us from using Xio

if it's something in my own browser, I don't know, but on my end, I did no new updates or software installs, so I assume it's nothing wrong with my browser, unless I may be missing something

so, can you please check it out and make some quick adjustments to make it work... 

thank you

**Comment by cobr123** [comment]
try this 12.0.123 https://github.com/cobr123/XioScript/blob/master/XS12.user.js

**Comment by Ghiby** [comment]
Hi there,

I've tried it, but as it is now, it won't automatically install under
chrome extensions, I gave me some kind of extension error and I had to give
it access to the link via tampermonkey, which I did anyway

as of now, I have it under Tampermonkey, I see it there, it's enabled, yet
still is not working for virtonomics, while in-game, still the XIO is not
working like it used to, it's like is not even enable, I have nothing from
the old XIO, no menus, no numbers on the main unit page, noting, like XIO
is not enabled or not functional - yet, once again, I have it enabled in
Tampermonkey, so it's there, but it's not having any effect, not operating
as intended

what else can we do? I am representing my team as well, they all told me
they have the same problem since that update the game admins did

thank you

**Comment by cobr123** [comment]
yandex browser 17.6.1.835 beta (64-bit)
Violentmonkey v2.5.7
![43](https://user-images.githubusercontent.com/82329/32404743-52f8f35e-c167-11e7-9acf-db907962d739.png)

**Comment by cobr123** [comment]
can you post here errors from console (F12) ?

**Comment by TeaMike** [comment]
Ghiby may have an installation issue like multiple installs;  12.0.123 basically works for me with some remarks:

- adding approx 350 stores to the script piles up to much temporary data and always results in a time-out. I need to use one separate LocalStorage to just run on the stores to make it work.
- i don't want to have 2x stock in my subdivisions; in case of restaurants and others it overloads the stock and makes the display of the system's warehouse icons useless. In previous XS versions i used to edit the script parameters to this, but with this version such modification results into errors: the script always orders "last sold" quantity instead of "full supply for maximum supply less overstock".

Also, i am still look for a fix to https://github.com/cobr123/XioScript-10/blob/master/XSUS.user.js because it runs the script on the stores in 4 minutes, instead of >20 minutes needed with 12.0.123

**Comment by TeaMike** [comment]
12.0.123 equipment repair for educational institutions and read towers doesn't work for me

**Comment by ezapata20** [comment]
script does not fork with chrome, can someone help with that. firefox keeps crashing

**Comment by Ghiby** [comment]
well,

first, I don't have an install error anymore, as it was just first time while following the link you posted here to the javascript itself, but as I mentioned above it asked me to give access to the link, which I did anyway, so now I don't have an error code anymore

however, is still not working for me and in this particular case I am here posting my comments not just for me, but also on behalf of our in-game team, from our party and corporation in Mary realm, they also are unable to see the XIO script working anymore, not since the day the game admins changed something in the interface

I see the screenshot you posted here and I am amazed how come it works for you, yet is not working for me anymore - I should mention again, it was working just fine for me too, with no problems at all (except multiple suppliers errors, but insignificant errors)

@ TeaMike
you mean I may have a problem with multiple installations of the XIO script? or the Chrome browser?

just to clarify, hoping we'll find a solution to this, I don't have multiple installations of the XIO script, unless there are or may be some automatic updates done by default in the background without my knowledge and/or permission like many applications do

however, under Tampermonkey, I only have one XIO listed, so I'm almost sure I don't have multiple installations

as far as Chrome browser, once again, only whatever new updates will install automatically in the background, but again I am not aware of multiple installations since I didn't do any new installs manually 

at this time, for me, still is not working - and same for some of my teammates using Chrome

my point is that ever since the game admins changed something in the interface, introducing a "new look" with some slight changes and improvements, especially preparing for their VCoins, it all made XIO script not to work anymore

I can handle it with no script, but I could use it once again since it's available and I like it, yet is not working for me anymore, again I'd like to point out it was working just fine for me and my teammates for years and years... something odd is happening... hehe...

thank you for looking into this...

**Comment by XiozZe** [comment]
Because XS12 will not be supported anymore, I close this issue.
