### ISSUE TITLE
Suggestion: tech Upgrade assistant

### ISSUE THREAD

**Issue by TeaMike** [XiozZe/XioScript#14]
Suggestion: function to 
-  “adjust equipment quality to required”
- “adjust worker quantity to the required” (labs only)
-  “adjust worker qualification to the required”

for all subdivisions including labs
Why: when introducing new tech (or starting higher study) onto a multiple of subdivisions equipment and worker quantity upgrade can be very tedious. 

Issues will reveal itself after one update trough ingame-icons: 
- new worker quantity, equipment quality my exceed top manager
- labs may be to small to accommodate new worker quantity
- enabled HR will overwrite the new worker qualification; ultimate reason to fix salary functions/insert target values 

the last one could be fixed by including the entry boxes provided by the HR system into the function

**Comment by XiozZe** [comment]
Planned in XS12

**Comment by XiozZe** [comment]
I consider adjusting worker quantity for labs to tricky regarding the top3.
All other points (adjust equipment and worker qualification) are implemented in XS 12.0.6
