### ISSUE TITLE
Suggestion: Marketing assistant for subdivisions

### ISSUE THREAD

**Issue by TeaMike** [XiozZe/XioScript#15]
Suggestion: set marketing expense to a multiple of city population (contact per citizen) and a sealing amount (tv ad only)

Why: a multiple of city population will result into the same popularity, independent from the city and its population. With the function for example using a multiple of 2 a popularity of around 490 will be achieved after some updates.

Executable on all type of service enterprises and stores

**Comment by XiozZe** [comment]
Planned in XS12

**Comment by XiozZe** [comment]
Added in XS 12.0.16
