### ISSUE TITLE
Suggestion: Group operation: Innovation manager

### ISSUE THREAD

**Issue by TeaMike** [XiozZe/XioScript#18]
- solar cells:
- add solar cell innovation in factory where the electricity cost is higher than 100k,  there is no other innovation installed in the same slot and the subdivision is not on holiday
- remove innovation with effectiveness 0

-in other subdivisions (mills, small factories, animal farms, stores etc) add quality boost and equipment service innovation if no other is installed in the same slot

In this regard i would like to remove all the existing innovations (except those paid by points) in order to run the above function so the innovations expire on the same date, reducing pm-clutter and necessity to re-install the innovations

**Comment by XiozZe** [comment]
Automatic purchase planned in XS12

**Comment by TeaMike** [comment]
sounds great. I'd love to UNINSTALL the current innovation  and then re-install it so to bundle the expiry of them.

**Comment by XiozZe** [comment]
Wouldn't that reduce the profitability of the factory? And what if I re-install all solar panels today and decide to build an extra factory tomorrow? With auto-purchase all you have to do is to ignore the solar panel messages. (With auto-purchase I really mean AUTO-purchase: no hands required.)

**Comment by TeaMike** [comment]
well my idea was to reduce the often daily messages that the innovation has expired and i don't mind spending extra $$ for that once a rl-year or so. 
For auto-setting the script would need to calculate if its worth to install solar panels and automatically install quality booster on level 1 factories and level 1 and 2 animal farms but going trough every subdivision (every day), we can ignore the expiry PMs and if you don't worry about the script needing to check every single subdivision every day then i guess its ok.

**Comment by XiozZe** [comment]
I don't know with all the fluctuations of the energy prices and such if I can let the script itself decide whether or not to buy the solar panels, but you will receive the choice of auto-purchasing the solar panels or not for every subdivision separately.

To do the same for quality boosters will be planned as well in XS12.

**Comment by TeaMike** [comment]
I should not check the tariff but the actual expense of electricity in each subdivision to decide on execution: 50% of that amount must be larger than setup of innovation/365  + daily cost of innovation ( and of course not touch existing innovation in the same slot).
There's a whole bunch of subdivisions which use very little electricity, take an apparel factory making sombreros it only costs 17'000 on electricity in a region where tariff is 10: buying solar panel would cost 5 Million/365 plus 50'000 per update = 67000 expense to save 8500 a day...

**Comment by XiozZe** [comment]
I will look in to it, but it will not be high priority.

**Comment by TeaMike** [comment]
well then i am not sure how it is a useful tool, looking forward to see more clues from you to better understand.

**Comment by XiozZe** [comment]
Solar panels (only) with savings-costs comparison available in XS 12.0.16
