### ISSUE TITLE
Suggestion: Building Shortener: remember last choice

### ISSUE THREAD

**Issue by TeaMike** [XiozZe/XioScript#21]
Building multiple units of the same kind in the same city seems common, if the script could remember the last selection on each screen we could just click thru "continue" and further cut down building time.

Additionally, clicking of "continue" button could be avoided like it is on the selection of factory type (steps 1?)

**Comment by XiozZe** [comment]
Building Shortener will not be supported in XS12, instead, it will focus on cutting maintenance time of the company rather than cutting the time of expanding your company

**Comment by TeaMike** [comment]
i'd probably keep 10.5 around since building 50 or 100 subdivisions takes really, really long without that building shortener.
