### ISSUE TITLE
bug:  equipment repair (all 4 functions)

### ISSUE THREAD

**Issue by TeaMike** [XiozZe/XioScript#23]
i'm getting errors "no equipment fulfilling the requirements"  with all subdivisions using high quality equipment where the supply window has more than one page on the "all" tab and my equipment is listed only on the second page.

This doesn't happen after i manually visit a factory (or laboratory), click "equipment" select "mine", close the window and run the script again on the subdivision list.

**Comment by XiozZe** [comment]
Solution to myself: first run a function that sets the number of subdivisions per page to 10.000, before running the equipment function. Optionally, reset back to the old number when complete.

**Comment by XiozZe** [comment]
Problem should be solved in XS12
