### ISSUE TITLE
Broken function: Display of Top Manager Stats

### ISSUE THREAD

**Issue by TeaMike** [XiozZe/XioScript#25]
The page unit/view has been overhauled; though there is a switch from new to old interface (which isn't adapted for all type of subdivisions), the Top Manager Stats aren't shown on the old interface anymore.

**Comment by XiozZe** [comment]
How big is the inconvenience regarding the new Virto-implemented Top Manager functions?

**Comment by TeaMike** [comment]
Well the stats are very helpful, but now gone. Considering the purpose of the script /and your screen size) the issue is at least thhhhhhhhiiiiiiiiiiiiiiiiiiiiiiiissssss big.
Maybe the script can't get the Top manager data properly anymore and thus displays nothing at all?

**Comment by TeaMike** [comment]
i just noted that XS 7.3 still shows the TM stats on the classic factory pages. Could it be that 10.5 simply hangs itself up because it additionally includes the stats including Q-Bonuses (and because the Top manager page was edited also) ?

**Comment by XiozZe** [comment]
XS 12 will be so powerful that there is a high chance that the top manager stats will be completely omitted

**Comment by TeaMike** [comment]
i am in no need of all the salary setting functions because i can't afford to pay for top salaries in every case. I often set it for example 10% higher than required without bonus but way below required with bonus.

**Comment by XiozZe** [comment]
Then I'll create a "Top Manager but not over 120% compared to the salary of required"-function. Something along those lines.

**Comment by TeaMike** [comment]
Just to clarify,  there's two versions higher than required which for some reason i am using:
a) required by tech b) required for max growth without bonus. 
Though i think maximum installable tech and maximum possible amount of workers are also important info provided by the TM function.

**Comment by XiozZe** [comment]
You can find the maximum installable tech under the second forecast, and for the maximum possible amount of workers, I can only find reason to use it if my top manager qualification is too low to fill a full subdivision with workers. But well, I did script it because of that reason in the first place.

Even though the Top Manager Stats are one of my most helpful and important functions ever scripted, I am really aiming to replace them.

**Comment by TeaMike** [comment]
well i do not understand why you'd want to abolish displaying this data. Many players still like to tinker with the settings, a script taking care everything and not displaying good info makes everything a bit mystical.

The max. possible workers is necessary when qualification is lower and a full load won't work. This drags on to higher qualification levels if the tech is higher the subdivision still works but with fewer workers. It is all things which larger players don't need to care but for players in their first rl-year of game that stuff seems important.

**Comment by XiozZe** [comment]
Just a bit of beauty, I guess?
Knowing that XS12 is just one button and a lot of drop-down boxes, it's a lot cleaner without those additional small stuff. But maybe I should ignore the artist inside me.

**Comment by TeaMike** [comment]
you're an artistic programmer, don't worry about the user interface to much, its all about usability and keep your efforts as small as possible at the same time

**Comment by XiozZe** [comment]
Top Manager functions fully supported
