### ISSUE TITLE
Problem with the latest version

### ISSUE THREAD

**Issue by seawerst** [XiozZe/XioScript#3]
When I get the most up to date version, including your latest checkin. I get some files that don't seems to exists anymore as they similar then the wiki
Creating-XioFunctions.md
Home.md
Install-XioScript.md
Using-XioScript.md
XioDictionary.md
XioFunction-API.md

Are you behind in your own merge? It's my first time with Github

**Comment by XiozZe** [comment]
Well, I'm still trying to learn to understand GitHub as well, as I'm not really familiar with it yet.
The merge was a test-merge to see what it does.
I do not really get what you mean though, how can I reproduce your problem?

**Comment by seawerst** [comment]
When I forked the project, I was behind in the commit queue, so I synch the two projects and know I have the files listed in the post in the root directory but they are not visible herehttps://github.com/XiozZe/XioScript. 
Now I'm 88 commit ahead and I could make a pull request for these files. They look like the wiki files.
![github](https://cloud.githubusercontent.com/assets/5280138/9478068/c42f4bd2-4b43-11e5-9d70-6bf6edaad148.JPG)

**Comment by XiozZe** [comment]
Hmm... 
I don't know about the wiki files, but why don't you pull the request and we'll find out what happens.
:D

**Comment by seawerst** [comment]
I just found out. Trying to merge your last check-in with my clone (I'm using this official add-on with Visual Studio https://visualstudio.github.com) I'm mixup the git repository with the wiki one. I did not know that the wiki had it's own database (https://github.com/XiozZe/XioScript.wiki.git)
