### ISSUE TITLE
Advertisement functions

### ISSUE THREAD

**Issue by XiozZe** [XiozZe/XioScript#30]
Add basic functions: zero, maximum (top manager), minimum TV.
Research the maximum amount of customer for Elite level (shops)
(three departments, size 100.000 m2 and <150.000 costumers is elite)

**Comment by TeaMike** [comment]
"Research the maximum amount of customer for Elite level "
i have at least 5 stores with 200k visitors on elite level, one of them with 3, 2 of them with 2 departments.
Is it possible this depends on player qualification ?

**Comment by TeaMike** [comment]
Effective advertising depends on popularity (which depends on the amount of contacts vs the population of the city.  Adding more departments seems to reduce the allowed number of contacts to maintain the elite status.

In very small cities (like Vaduz)), min.  tv advertising is already to much for maintaining the elite level.

**Comment by XiozZe** [comment]
The (three departments, size 100.000 m2 and <150.000 costumers is elite) were in the city centre, and used my VirtoScript to keep the advertisement below 150.000 for months. Based on qualification is possible but in my mind highly unlikely. I do not have data from a year ago but if I remember correctly the script ended up with lots of different advertisement budgets and popularity ratings throughout all the stores to keep the number of customers between the 100k and the 150k (125k +- 20%), but all the stores did have their limit on 150k.

**Comment by XiozZe** [comment]
Maybe we can do a large-scale data collection (with the use of scripts) to compare the amount of customers with other variables. If four or five large scale companies run a one-button data generator script (which I'll write) we should be able to easily gather data on >1000 stores. Then we just have to compare the values.

I thought of these variables:

- Store size
- District
- Popularity
- City population
- Required number of contacts (from the advertisement page)
- Service level
- Holiday On/Off
- Total Efficiency

Missing something?

**Comment by TeaMike** [comment]
Service level depends on a few more factors:
http://wiki.virtonomics.com/index.php/Principles:Commerce#Service_Level

i'll gladly cooperate for the data collection.

**Comment by XiozZe** [comment]
It is true that a High service level can not always be blamed on the number of visitors, but if you only look at it the other way around: every visitor count with an Elite service level is a visitor count below the maximum, and so we just have to look for the highest value possible there.

**Comment by XiozZe** [comment]
I guess I will keep it and the basic functions in XS 12.0.16
