### ISSUE TITLE
Bugs and suggestions: Xio overview

### ISSUE THREAD

**Issue by TeaMike** [XiozZe/XioScript#39]
What a cool solution.. you gotta buy a new shelf for all the new kudos you're gonna collect ;)

there's some bugs with _generate_ function, i tested it by just browsing each specific type of subdivisions:
- _generate all_  on factories gets stuck at exactly 1000 server calls
- _generate all_  hangs on warehouses, laboratories, mills, animal farms. 
Test on 25 animal farms after failing "generate all" i browsed 25 animal farms and clicked _generate_ on single lines: it worked for the first bunch of subdivisions then hung up the script. Skipped this subdivision, the next one worked again. Then i clicked the last subdivision at the bottom of the list and: the second last subdivision was generated! A few more times, the subdivision above the clicked one was generating and i ended up with 3 subdivisions which still didn't had any setting.
So i went to their main page to select "maximum salary", then back to reload the overview and execute  _generate_ (all or personal) but it didn't make the missing selectors appear,  however, the script finished with the "all done" message instead of hanging itself.
- the same test on factories had the exact same pattern

- entries "price" and "policy" in medical centres appear but only on some of the subdivisions on the list

**suggestions**
- display the filter "by type"
- display country flag and city name
- add button hide/unhide pop up selectors when they show "don't"
- add button to minimise a column width to avoid getting lost at column 7
- add the “on holiday icon” and the on/off holiday function
- add all other icons from the subdivision list
-  to restore the user's freedom of applying/modifying functions to any selection of subdivisions, make XSOverview work with the script "unit list filter" 
   https://greasyfork.org/scripts/1535-virtonomica-управление-предприятиями
and add selector to the function column header with a little button to apply the setting to all browsed subdivisions
- display content from the script “notes” , stored in the local storage with key “notes”, and “values” stored in a single line like this: {"3304341":{"text":"recheck","time":1455360896741,"name":"RT OCIM'TrONics","type":"Warehouse","link":"http://virtonomics.com/mary/main/unit/view/3304341"},"3764819":{"text":"2-26 recheck","time":1456319329527,"name":"Cardiology","type":"Medical center","link":"http://virtonomics.com/mary/main/unit/view/3764819”}}

script location: https://greasyfork.org/scripts/1540-virtonomica-notes/code/Virtonomica:Notes.user.js

**Issue alerts**

- “equipment" fixing function on animal farm appears, it could cause trouble with insufficient grain quality

- Price setting problem scenario: a factory's supply broke, on the last day of production only 5 pieces were produced and a new sales price is set according to the sky-rocketing new prime cost.   Once production is resumed at full,  production price drops back again to normal but the sales contracts are still served at the sky-high price for one update.This may drag on on to all follow-up factories, warehouses etc and creates huge losses on tax and customs.  >> Limit automatic price changes to for example 5 or 10% a day.

**Comment by XiozZe** [comment]
I am not able to reproduce _any_ of your generate all bugs: I clear my localStorage, I use the generate all button and the function works splendidly on all subdivisions, hospitals, factories, animal farms and warehouses a like.

Isn't there also a "Q2.00"-equipment function? It is able to repair a subdivision with only Q2.00 equipment. Maybe you are that rich bastard that can afford supplying your chickens with an increasing quality of grain, and therefore you are in dire need of that Required function. And if not, you will learn from experience that you have to use that other option. I can make life easier, but I'm not going to play the game for you.

Regarding the price setting problem: I think that refreshing the contract daily would be the optimal solution. Refreshing would update the price to the latest set: solving the problem. I will have to experiment though if that wouldn't lead to a lower ranking in the contract order list, but I think not.

I will look at your suggestions on a later date.

**Comment by TeaMike** [comment]
I can't empty the local storage because its used for other scripts. I might move it away temporary so it creates a new one, will see 

Equipment 2.0: got it.

i've just did the same as above on a few warehouses, yet again the same buggy thing happened.
Then did maintenance on some warehouses for the CTIE setting only, it seems ok but said its repairing equipment, too ?

**Comment by XiozZe** [comment]
I'll think I have a solution I'll try out tomorrow

**Comment by XiozZe** [comment]
The Generator function is altered in XS 12.0.9.
Regarding the price setting problem scenario: the problem will magically solve itself when the [new interface](http://virtonomics.com/mary/forum/forum_new/11/topic/105397/view/m:99929162/#99929162) is implemented on warehouses as well. Until that time, I will see if I can do something.

**Comment by XiozZe** [comment]
The Generator functions should work now (although I have no base to speak from because for me it worked before as well). The price setting problem should be solved with the price updating.

I have cleaned up the XioOverview a bit but I'm not going to work on it more than this. HTML and CSS are just not my thing. I prefer to continue with the advertisement functions.

**Comment by TeaMike** [comment]
could you make the ![holiday icon](http://virtonomics.com/img/unit_indicator/workers_in_holiday.gif) visible on the XioOverview please

**Comment by XiozZe** [comment]
I do not plan to add the column of the main page, because that icon is never up to date. But I might first load the holiday/employees management overview and add the icon based on that info.

**Comment by TeaMike** [comment]
even better :100:

**Comment by TeaMike** [comment]
Any chance for full repair (incl red ones),  price empty stock and full service appearing sometimes soon?

**Comment by XiozZe** [comment]
I had price empty stock and service planned for this weekend. I will add full repair as well.
