### ISSUE TITLE
Suggestion: TM stats: Display first decimal of maximum tech level 

### ISSUE THREAD

**Issue by TeaMike** [XiozZe/XioScript#40]
maximum tech level 26.1, 26.2 etc. because a higher tech level  can be installed without loss of efficiency already when max tech level is at 20.8. The rounding to a full tech level covers up some opportunities there :)

**Comment by XiozZe** [comment]
Does that mean a higher level of technology can be set than the maximum value, and so it can exceed the values given here?
http://calc.atlantis-corp.ru/top3.php
(first column is top manager level, third column is technology)

**Comment by TeaMike** [comment]
yes,  qualification grows gradually and the closer to the the next higher requirement level the smaller the penalty on efficiency; it vanishes before the actual required level / full number value for that technology is reached.
It also works when salaries and worker quantity aren't maxed out.

For plantations and agriculture, where players usually only hired a fraction of the possible workers, at least a full level higher than suggested can be installed without harm on efficiency.

**Comment by XiozZe** [comment]
Very well, it is rounded down to one decimal in XS 12.0.9
