### ISSUE TITLE
12.0.17 doesn't load

### ISSUE THREAD

**Issue by TeaMike** [XiozZe/XioScript#48]
installed but not showing any buttons

**Comment by XiozZe** [comment]
Here it runs on Chrome and Firefox.
What does the console log show? (most importantly: "XioScript 12 is running!")

**Comment by TeaMike** [comment]
12.0.15 worked fine, didn't try 16, but 17 and 18 definitely don't work in Safari browser.

Safari console throws a ginormous  list of errors, its to long to post here so i've sent it to you by email.

**Comment by XiozZe** [comment]
I'll pick up Safari to see what I can do.
I am familiar with the long list of errors you have sent me. However, those are all errors from JSHint, which is a stylistic syntax corrector. The lines you see aren't actually wrong, my lines are just not the same as the 'standard'.

The real error was at the bottom:
[Error] SyntaxError: Unexpected token '>'

**Comment by XiozZe** [comment]
Is it fixed?

**Comment by TeaMike** [comment]
safari shows a very long list of errors when Generate All is clicked but appears to do the job anyway till “all done”. The errors start with  

[Error] Failed to load resource: the server responded with a status of 500 (Internal Server Error) (salary, line 0) http://virtonomics.com/mary/main/company/view/2202845/unit_list/employee/salary

[Error] Deprecated attempt to access property 'keySystem' on a non-MediaKeySession object.
	extend
	extend
	Oc
	ajaxSetup
	ajax
	(anonymous function)
	(anonymous function) unit_list:32:134
[Error] Deprecated attempt to access property 'sessionId' on a non-MediaKeySession object.
	extend
	extend
	Oc
	ajaxSetup
	ajax
	(anonymous function)
	(anonymous function) unit_list:32:134
[Error] Deprecated attempt to access property 'onwebkitkeyadded' on a non-MediaKeySession object.
	extend
	extend
	Oc


and so on.

—————————————

When i click XioOverview to leave the overview i am getting another huge list of errors starting with

Deprecated attempt to access property 'nodeType' on a non-Node object.
extend
extend
Oc
ajaxSetup
ajax
(anonymous function)
(anonymous function)unit_list:33:134

and so on.

—————————————
let me know if you need the full error list.


Meanwhile, in Chrome when going to see XioOverview a list of displaced data shows up at the bottom of the subdivision list:

http://tinypic.com/m/jgqtjl/4

**Comment by XiozZe** [comment]
Ahh that bottom list of holiday data contains all the data about the subdivisions that are not shown on the page. If you set your page view to 10,000 it will disappear :P 

I do not get the errors myself if I run XioGenerator on Safari, so I guess you can just ignore them
