### ISSUE TITLE
XioOverview: subdivision on holiday

### ISSUE THREAD

**Issue by TeaMike** [XiozZe/XioScript#53]
Desperate for seeing the holiday icon the overview; now i dunno which subdivisions i should set (price, supply, ADVERTISING).  What does XS now actually do with subdivisions on holidays?

**Comment by XiozZe** [comment]
All functions run on, no matter whether they are on holiday or not. The only issue would be wasted time. By the way, if you manage the holidays using the 'holiday' column, then shouldn't you know which subdivisions are on holiday and which aren't?

**Comment by TeaMike** [comment]
i just added "advertising" to the above.  Right now this is about initial settings, the lack of holiday indicator requires to visit all subdivisions anyway just to verify that status.

Also, XS 10.5 is still a lot more practical for a quick holiday on/off setting because it doesn't require loading XS overview and switching the setting on and off each time. I am switching on and off a couple of subdivisions almost every day but they're across various subdivision types.

**Comment by XiozZe** [comment]
Holiday text added in XS 12.0.19
