### ISSUE TITLE
Add translation support to selectors

### ISSUE THREAD

**Issue by cobr123** [XiozZe/XioScript#54]
Hello, i play on russian version of virtonomics and when i set "salary" to "requied" i get wrong values of workers qualification, but when i switch to english interface, script works fine.

**Comment by XiozZe** [comment]
Hello!
Problem will be solved in version XS 12.0.19.
I now see that there are plenty of problems with top manager related functions, that work on the English realm but not on the Russian realm, so I'll plan to fix that as well.

**Comment by XiozZe** [comment]
The required function should work now.
Also, the top manager related functions should work the same on the Russian realm as on the English realm.
Can you further check for me if there are bugs relating to language in there?

**Comment by cobr123** [comment]
Sure
