### ISSUE TITLE
Export/Import

### ISSUE THREAD

**Issue by TeaMike** [XiozZe/XioScript#57]
Could this backup function, conveniently, be made thru a file from/to the desktop? 

I've tried to import something to see if it overwrites the existing but nothing happened after clicking "save!".

**Comment by XiozZe** [comment]
To the desktop could be possible.
From the desktop however is restricted due to privacy. (You don't want a script that can access your desktop).

If nothing happens after clicking save, your text is corrupted.

Can you test it a few times by exporting-importing to different browsers?

**Comment by TeaMike** [comment]
going trough "open/select file" just like uploading an image to free image host, and a "save to" dialogue would probably be safe.

I've copy-pasted export settings from safari to chrome, seems to have worked but there's no conformation. What happens with duplicate instructions in this case now? How can i wipe the infos stored in the storage?

**Comment by XiozZe** [comment]
I'll see what I can do. 

You can clear your localStorage (FF/Chrome) by putting this line of code in the console log:

`for(var key in localStorage) localStorage.removeItem(key)`

After you have pressed "save", the page should reload, or show in the console log that the import was unsuccessful. The Import function overrides any options you have set, but does not delete options.

**Comment by TeaMike** [comment]
Does that delete ALL local storage or only the entries by XS?

**Comment by XiozZe** [comment]
All.

Need something more specific?

`for(var key in localStorage) key[0] === "x" && localStorage.removeItem(key)`

**Comment by TeaMike** [comment]
yes, thats great coz i've got other scripts using ls. 

Thank you Sir and don't forget looking for the easter nest ;)

**Comment by TeaMike** [comment]
I hope proper backup e.g. Import/Export is available in the next XS version

**Comment by XiozZe** [comment]
And it is. I don't even have to do anything for it. XS14 is an add-on and if you sign in in Firefox you can sync your add-on settings.
