### ISSUE TITLE
Equipment purchase

### ISSUE THREAD

**Issue by TeaMike** [XiozZe/XioScript#58]
I'd like to FIRE a function in my subdivision to buy equipment in a factory/animal farm.

Also, since you've added such selectors for warehouses, to set purchases to supply from my own company/corporation/any/others only.

**Comment by XiozZe** [comment]
I'm planning to do an equipment function based on the number of employees (so based on the equipment needed).

You are talking about the warehouse supply function that adds suppliers from the world market itself right? That would indeed need a "Mine"/"World" option.

**Comment by TeaMike** [comment]
hm.. i guess so...  just a restriction to the purchase of equipment. 

I realise now that didn't think to much about how tricky such equipment purchase function could be, given there might not be sufficient quantity available from a single point of sale.

**Comment by XiozZe** [comment]
Equipment is very tricky.
The current equipment function is still not bug free. It should buy all the necessary equipment in one round, but every day it seems to skip some buildings. Once I got that down, I might be further working on the extension of the function.

**Comment by TeaMike** [comment]
i recently had a qualification bonus expiring and on the next day i found several dozens of subdivisions with insufficient quality of equipment.

This equipment upgrade assistant: https://greasyfork.org/en/scripts/8452-virtonomica-Апгрейд-оборудования
is very helpful to display the quantity of equipment to be replaced in this situation, though it would be great to have an automated solution which use useful after tech upgrade, too.

**Comment by XiozZe** [comment]
Equipment Purchasing has been added to XS14.
