### ISSUE TITLE
XioScripts gets frozen

### ISSUE THREAD

**Issue by Trebia** [XiozZe/XioScript#60]
Just running the script in Google Chrome and looks to get frozed. Essentially it stops when reaching the equipment part, however it is not consistent sometimes gets 33 done other times is reaching 34.

XS 12 Maintenance Log
Supply	0	of	12	
Salary	0	of	37	
Equipment	33	of	36	
Solars	32	of	32	Done!
New suppliers:	0
Get calls:	77
Post calls:	36
Total server calls:	113
Time:	9	min	25	sec

**Comment by XiozZe** [comment]
First, check if you are using version 12.0.19 or version 12.0.20 (and not some older version).

In XioOverview, there is the "Equipment" button on the top row where you can fire only the equipment function. By setting the options back to "-" and trying them one at the time or in bunches, you can find out which subdivisions are causing the problem.

It would be a huge help if you could determine:
-what the main difference is between the subdivisions that do work and the subdivision that don't
-which subdivision type it is
-how much is left to repair
-if there is actually a supplier on the market that could be used
-and anything else that looks relevant

**Comment by Trebia** [comment]
Using 12.0.20

It looks that the problem is bigger, when clicking on XioOverview the script is not behaving as expecting (actually there is nothing visually happening).

Is there any incompatibility with AddBlock?

**Comment by XiozZe** [comment]
Adblock should have nothing to do with it, although I can never be certain.
What is your OS, browser, realm and virtonomics language?

**Comment by Trebia** [comment]
Windows 10 
Google Chrome (can use another)
Spanish as virtonomics language (I am happy to change to French or English)
Realm Mary
Script version 12.0.20
TamperMonkey for running the script

How can I help better the debugging? I am not experienced in javascript, but I have java knowledge

**Comment by XiozZe** [comment]
Try the English version first, to see if that solves the issue.
Debugging can be really difficult, but maybe you can hunt an error for me:
if you open the console log (F12), copy the most bottom error you see, something like
`[Error] SyntaxError: Unexpected token '>'                                                                      VM299:723`

**Comment by Trebia** [comment]
You found it!

I discover the following (if you want I can create different issues for each of them):

- When you create your settings in one language (spanish) and enter in another one (english) they are not saved.
- (info) If you export from one language (spanish) to another (import) (english) is working ok.
- XioOverview is not working in Spanish environment.
       The ouput of the log is: XioScript 12 is running! (is not working)
- XioMaintenance is giving me a failure in Spanish.
      - However when I opened english version and came back to spanish version is started working.

**Comment by XiozZe** [comment]
In the end, I have found a really simple solution to the XioOverview problem, but more interestingly: different languages work like different sites, each with their own localStorage and so their own options. Also the bug you encountered with the hanging on 33/34, is something I also experienced, but only on the side languages. It feels completely random though, as it just sometimes like to crash.   Anyways it is because of a server overload error, something that does not happen on the English server. But my script is smart and will try it again three seconds later so it continues. (I already scripted that part just in case but it seemed that it was bugged.) The XioOverview for languages other than English will be supported in XS 12.0.21.

**Comment by Trebia** [comment]
Happy to be an Spanish beta tester if needed.

Want also get proposals for improvement? (new nice functionalities)

**Comment by XiozZe** [comment]
If you could just report any bug that crosses your path I will be grateful.
And of course, I will appreciate any suggestions you leave here in the issues.

**Comment by Trebia** [comment]
Just seen the version 12.0.21 and tested it. It seems that all problems are fixed.

**Comment by A-root** [comment]
Yesterday I updated the script to the latest version 12.0.21, after updating the script does not shut down and works until you refresh the page. After much anguish have found that this occurs at the time of processing equipment and me hanging the next line Equipment  551 of 584. 
If open the log console I see "Uncaught TypeError: cannot read property 'available' not VM794:1683"
