### ISSUE TITLE
Restaurant buying maximun supplies

### ISSUE THREAD

**Issue by Trebia** [XiozZe/XioScript#64]
It happened the following:

- Restaurant, supply set to 3x Stock
- Consumption around 20
- Script version 12.0.20

It was expected that the order of magnitud of purchases to be around 60 as maximun. The actual buy was the maximum provided by the supplier, in this case 25000.

**Comment by XiozZe** [comment]
The restaurant supply function uses the maximum consumption of the restaurant as required. So it buys three times required minus the stock.

**Comment by TeaMike** [comment]
most restaurant types are overstocked with 3x supply, i never got a grasp on the concept of 3x.

Either it was you, or i did it myself, to change this function in XS 10.xx  to 2x.

**Comment by XiozZe** [comment]
Well, in fact they should be overstocked with just the double amount, not 3x.
It's 3x stock = 3x required - stock.
If 3000 is required, it will be break even on a stock of 6000, as it will buy 3x3000 - 6000 = 3000 for the next day, and 3000 will be sold on the next day.

**Comment by Trebia** [comment]
I double checked the documentation. I think it is clearly a wrong understanding of how teh scripts works.
I have modified the wiki marking in bold the word "maximum" for supply, so next rokie in the script will not face the same issues.

I propose to close this topic as it is clearly a wrong usage.
