### ISSUE TITLE
Add warning when lack of supply

### ISSUE THREAD

**Issue by Trebia** [XiozZe/XioScript#65]
This is the situation:
- I set the supply of a farm to 3xSupply.
- The supplier ran out of stocks.
- I have a need of 32000
- I have 64000 in stock.
- 3x should request 32000 to the supplier.
- I run the script and the request to supplier was set to 32000, but the expected delivery was 0.

The script did not provided any warning on the lack of supply. It will save important time going and checking each subdivision.

**Comment by XiozZe** [comment]
Well, sure

**Comment by XiozZe** [comment]
Lack of supply warnings are supported in XS14
