### ISSUE TITLE
Salary required "no limits"

### ISSUE THREAD

**Issue by Trebia** [XiozZe/XioScript#66]
In a situation with low qualitification required from employees (early stages of development of skill for the top manager) the required qualification (and so salary) of the employees is very low, so that the salary goes down the 0.8 city's salary.

I am proposing to add a feature allowing "Required no limits" that will allow go down 0.8 city's salary.

**Comment by XiozZe** [comment]
I'll add that option.

**Comment by XiozZe** [comment]
Option added in XS 12.1.0
