### ISSUE TITLE
XioOverview modification

### ISSUE THREAD

**Issue by Trebia** [XiozZe/XioScript#72]
I have just noticed that when modify the settings of the subdivisions in XioOverview mode, the changed data is not stored.

**Comment by XiozZe** [comment]
You sure?
You mean: you change an option, reload, and your option is not saved?

**Comment by Trebia** [comment]
Yep
version 12.0.21
Tested in a factory moving trainig to "City Salary"
Google Chrome

After modifying I reloaded the webpage.

**Comment by XiozZe** [comment]
XS 12.1 offers a completely new way of storing data and changing options. If bugs occur with the new not-yet-released version, please open a new issue.
