### ISSUE TITLE
XioScript gets stopped in a laundry

### ISSUE THREAD

**Issue by Trebia** [XiozZe/XioScript#75]
I have been am able to reproduce this error.

I have a laundry with the following setting:

Salary: Required
Training: 1 year
Equipment: Maximal, Black

Current status when making the test: 1 equipment in "black".

When firing (both by XioMaintenance and FIRE! button) the XioScript gets stopped without progressing. Console provides the following error:

> advert.png:1 GET http://virtonomics.com/img/qualification/advert.png net::ERR_BLOCKED_BY_CLIENT

When removing "Maximal" and replacing by "Required" or "-" the script works.

**Comment by XiozZe** [comment]
Problem solved in next update.

**Comment by XiozZe** [comment]
Reopened as the solution may have been lost in the transition between 12.0 to 12.1.
The script in not updated yet though.
