### ISSUE TITLE
hanging 12.0.21

### ISSUE THREAD

**Issue by cobr123** [XiozZe/XioScript#79]
![24](https://cloud.githubusercontent.com/assets/82329/14864767/0a55c48c-0cc4-11e6-9034-8caed8050bc3.png)

**Comment by cobr123** [comment]
add link to current processing unit in log

**Comment by cobr123** [comment]
last message in console 
Object
amount: 6
offer: 3290585
op: "repair"

**Comment by Trebia** [comment]
I have noticed is happening with restaurants and services. I reported this issue before, and I have got a message that will be solved.

**Comment by cobr123** [comment]
![25](https://cloud.githubusercontent.com/assets/82329/14864990/313a58d2-0cc5-11e6-93e0-b1b1b820b8eb.png)

**Comment by cobr123** [comment]
ok

**Comment by cobr123** [comment]
found example
![26](https://cloud.githubusercontent.com/assets/82329/14865670/56b5d91c-0cc8-11e6-81ad-5ed94b058320.png)
XioScript 12 is running!
VM485:3689 1.0771428571428572
VM485:3694 Infinity 0.9882236551347747
VM485:3787 1.0771428571428572 0.9882236551347747 Object {employees: 0, salaryNow: 0, salaryCity: 0, skillNow: 0, skillReq: 0…}
VM485:3683 [100, 106.44580513880288, 118.58683861617298, 129.25714285714284, Infinity, Infinity]


VM485:3027 XM!
VM485:3046 Object {}
VM485:1682 Uncaught TypeError: Cannot read property 'available' of undefined

**Comment by XiozZe** [comment]
I have fixed it already three weeks ago, but because I am focusing on XS12.1, and do not have a lot of time on my hands, I haven't updated XioScript in a while.

**Comment by cobr123** [comment]
again hovered today

**Comment by cobr123** [comment]
workaround: switch from required to maximal

**Comment by TeaMike** [comment]
please fix this issue caused by equipment repair "required"

**Comment by cobr123** [comment]
I fixed some bugs and added a couple of new ones) try this fork https://github.com/cobr123/XioScript in anticipation of the release

**Comment by XiozZe** [comment]
Wow, great! I didn't expect any coding support whatsoever, so this is a very pleasant surprise.
I'm afraid that I do not have any time to look at it nor push it through in the next coming three weeks due to exams, which is also the reason I haven't done anything in the last month. I'm making good use of my own script as I press the button once a day and then leave.
