### ISSUE TITLE
Supplier issue in factories

### ISSUE THREAD

**Issue by Trebia** [XiozZe/XioScript#80]
I am getting several error messages recently at factories :

Subdivision xxxxxx is missing a supplier, or has too many suppliers!

However each product has got a single supplier and suddently appeared this week, maybe some changes in the virtonomics webpage?

**Comment by XiozZe** [comment]
Yep:
http://virtonomics.com/mary/forum/forum_new/11/topic/105397/view/m:99929857/#99929857

**Comment by XiozZe** [comment]
Fixed supply function will be supported in XS 12.1.0
