### ISSUE TITLE
Suggestion: training variation

### ISSUE THREAD

**Issue by TeaMike** [XiozZe/XioScript#86]
i train most of my subdivisions until a 4 week training yields less than 0.1 additional qualification; the result is sometimes close but often 10-20% below city salary.

**Comment by XiozZe** [comment]
Option added in XS 12.1.0.
Do you have a lovely, less than 10 characters long name for it? Can't come up with a good one

**Comment by TeaMike** [comment]
sweet addition! lovely naming ? hmm.. how about *EcoLimit*  (i actually stop at 0.12, usually)

**Comment by XiozZe** [comment]
EcoLimit it will be.
