### ISSUE TITLE
Avoid infinite loop

### ISSUE THREAD

**Issue by Trebia** [XiozZe/XioScript#88]
I have noticed thaat the supply option might lead to an infite loop. Having 2 warehouses suppying the same product and allowing the script internal buy that might lead to the situation where one warehouse buys the other and viceversa, reaching to increasing demand and sales.

**Comment by XiozZe** [comment]
Due to a number of these bugs but also some game changing hacks (which I'm not going to give away), the automatic contract accumulation of the warehouse supply function will be abolished.
