### ISSUE TITLE
Bug/cost trap: price setting at factories

### ISSUE THREAD

**Issue by TeaMike** [XiozZe/XioScript#90]
i've warned about this earlier, now it happened to me that 've lost about 20B in taxes during the last 2 days: 
- lack of supply in one factory, only few units are produced > prime cost explodes and sales price set by XIO accordingly. On the next day existing contracts still sold at that super-high price, creating a totally unnecessary and unrecoverable loss.

http://i68.tinypic.com/t9bjex.png

**Comment by TeaMike** [comment]
Today i've lost 77B on taxes due to above issue

**Comment by XiozZe** [comment]
I'll add a new holiday option: "set on holiday if there is not enough production for a full round". Do you have any other proposed solutions for this problem?

**Comment by TeaMike** [comment]
that may not be sufficient if the subdivision
- runs with less than full supply (requiring XIO to be off for supply)
- is attached to a laboratory

A log error message should do the job, like
warning: the selling price has been increased by more than (30%?) in subdivision 12345678

**Comment by XiozZe** [comment]
The 'Price Hike' option, a warning for too big price increase, has been added in XS14.0.6
