### ISSUE TITLE
Bug:Version 12.0.21 needs repetitive running

### ISSUE THREAD

**Issue by Trebia** [XiozZe/XioScript#92]
I have noticed that the current version 12.0.21 has some troubles with the equipment. Apart from the issue #79 which I am facing as well, I have noticed that running equipment requires running several times "XioMaintenance" and each time one category of equipment is fixed (all machinery, then all research...)

**Comment by XiozZe** [comment]
I have finished rescripting the Equipment function for XS 12.1. It should work much smoother now albeit a little bit slower as it attacks the subdivisions one by one, and it even checks if all equipment is really repaired.

Therefore all equipment issues (#75, #79, #83, #91 and #92) should be solved. If not, open a new issue.
